name: PR checker

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  install-deps-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          cache: 'npm'

      - name: Install deps and check types/linter
        run: |
          npm install
          npm run lint
          npm run check-types
